### ISSUE TITLE
Stratum still panics on share submission

### ISSUE THREAD

**Issue by pool2mine** [etclabscore/core-pool#7]
I tested con ETC and it works fine, but when i try to connect to ropsten or ethereum it still crashes after a share is submitted. I checked proxy/miner.go and the Etchash go module code is there, somehow is not working for ethereum and ropsten

```2022/03/20 19:49:53 New block to mine on main at height 12112081 / 0x29b1610e / 7513059825
2022/03/20 19:49:53 Broadcasting new job to 1 stratum miners
2022/03/20 19:49:53 Jobs broadcast finished 40.257µs
2022/03/20 19:49:53 Cached stale JobID 06ca0966
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7dffce]

goroutine 451 [running]:
github.com/etclabscore/go-etchash.(*Light).getCache(0xc0003c6200, 0xb8d0d1, 0x40)
        /home/pool2mine/go/pkg/mod/github.com/etclabscore/go-etchash@v0.0.0-20210517131846-9a3cc202249e/etchash.go:513 +0x46e
github.com/etclabscore/go-etchash.(*Light).Compute(0xc0003c6200, 0xb8d0d1, 0xb14a43beb61efed3, 0x66a5a3f10c6d8a7a, 0x6006b32c528ddada, 0x4a8de0cb56dd7999, 0xf7ef1000547c3b61, 0x0, 0x0, 0x0, ...)
        /home/pool2mine/go/pkg/mod/github.com/etclabscore/go-etchash@v0.0.0-20210517131846-9a3cc202249e/etchash.go:469 +0xab
github.com/etclabscore/core-pool/proxy.(*ProxyServer).processShare(0xc0000b52c0, 0xc00007a060, 0x2a, 0xc00013862b, 0x8, 0xc000026800, 0xd, 0xc0001d80e0, 0xc00043b3b0, 0x3, ...)
        /home/pool2mine/OEP-NH/proxy/miner.go:51 +0x1c9
github.com/etclabscore/core-pool/proxy.(*ProxyServer).handleSubmitRPC(0xc0000b52c0, 0xc0000a00d0, 0xc00007a060, 0x2a, 0xc00013862b, 0x8, 0xc00043b3b0, 0x3, 0x3, 0x85dcc0, ...)
        /home/pool2mine/OEP-NH/proxy/handlers.go:81 +0x355
github.com/etclabscore/core-pool/proxy.(*ProxyServer).handleTCPSubmitRPC(0xc0000b52c0, 0xc0000a00d0, 0xc00013862b, 0x8, 0xc00043b3b0, 0x3, 0x3, 0x2, 0x2)
        /home/pool2mine/OEP-NH/proxy/handlers.go:53 +0xef
github.com/etclabscore/core-pool/proxy.(*Session).handleTCPMessage(0xc0000a00d0, 0xc0000b52c0, 0xc000136aa0, 0x841cc0, 0xc000136aa0)
        /home/pool2mine/OEP-NH/proxy/stratum.go:432 +0x2099
github.com/etclabscore/core-pool/proxy.(*ProxyServer).handleTCPClient(0xc0000b52c0, 0xc0000a00d0, 0x1, 0x0)
        /home/pool2mine/OEP-NH/proxy/stratum.go:120 +0x270
github.com/etclabscore/core-pool/proxy.(*ProxyServer).ListenTCP.func3(0xc0000b52c0, 0xc000134030, 0x9aba00, 0xc000010040, 0xc000160000, 0xc0000a00d0)
        /home/pool2mine/OEP-NH/proxy/stratum.go:82 +0x39
created by github.com/etclabscore/core-pool/proxy.(*ProxyServer).ListenTCP
        /home/pool2mine/OEP-NH/proxy/stratum.go:81 +0x6d1
pool2mine@pool2mine:~/OEP-NH$
```

**Comment by 0xTract0r** [comment]
My pool is normal, and mined many block in eth mainnet.

**Comment by chrisfranko** [comment]
so how do you compile this?
